blank_issues_enabled: true
contact_links:
  - name: OwnCrew Core Security Policy
    url: https://github.com/owncrew/owncrew/blob/master/SECURITY.md
    about: View security policy
  - name: OwnCrew Core Developers
    url: https://owncrewcore.org
    about: OwnCrew Core homepage
